# JWT Centralized Service Test Script
# Run this script to test the JWT centralized service integration

# First, start your centralized JWT service on port 8091
Write-Host "=== JWT Centralized Service Integration Test ===" -ForegroundColor Green

# Test 1: Check if the application starts successfully
Write-Host "`n1. Testing application startup..." -ForegroundColor Yellow
Write-Host "Run: mvn spring-boot:run" -ForegroundColor Cyan
Write-Host "Expected: Application should start on port 8080 without errors" -ForegroundColor Gray

# Test 2: Test login with centralized service
Write-Host "`n2. Testing login with centralized JWT service..." -ForegroundColor Yellow
Write-Host "Command:" -ForegroundColor Cyan
Write-Host 'curl -X POST http://localhost:8080/api/v1/auth/login \' -ForegroundColor White
Write-Host '  -H "Content-Type: application/json" \' -ForegroundColor White
Write-Host '  -d "{\"username\": \"admin\", \"password\": \"admin123\"}"' -ForegroundColor White
Write-Host "Expected: Should return JWT token generated by centralized service" -ForegroundColor Gray

# Test 3: Test token validation
Write-Host "`n3. Testing token validation..." -ForegroundColor Yellow
Write-Host "Command:" -ForegroundColor Cyan
Write-Host 'curl -X POST http://localhost:8080/api/v1/auth/validate \' -ForegroundColor White
Write-Host '  -H "Authorization: Bearer YOUR_JWT_TOKEN"' -ForegroundColor White
Write-Host "Expected: Should validate token using centralized service" -ForegroundColor Gray

# Test 4: Test token revocation
Write-Host "`n4. Testing token revocation..." -ForegroundColor Yellow
Write-Host "Command:" -ForegroundColor Cyan
Write-Host 'curl -X POST http://localhost:8080/api/v1/auth/revoke \' -ForegroundColor White
Write-Host '  -H "Authorization: Bearer YOUR_JWT_TOKEN"' -ForegroundColor White
Write-Host "Expected: Should revoke token via centralized service" -ForegroundColor Gray

# Test 5: Test fallback mechanism
Write-Host "`n5. Testing fallback mechanism..." -ForegroundColor Yellow
Write-Host "Steps:" -ForegroundColor Cyan
Write-Host "1. Stop the centralized JWT service (port 8091)" -ForegroundColor White
Write-Host "2. Try login again" -ForegroundColor White
Write-Host "3. Should fallback to local JWT generation" -ForegroundColor White
Write-Host "Expected: Application should work with local JWT when centralized service is down" -ForegroundColor Gray

# Configuration test
Write-Host "`n6. Configuration options..." -ForegroundColor Yellow
Write-Host "To disable centralized service:" -ForegroundColor Cyan
Write-Host "Set jwt.enable-centralized-service=false in application.properties" -ForegroundColor White
Write-Host "To disable fallback:" -ForegroundColor Cyan
Write-Host "Set jwt.centralized-service.enable-fallback=false in application.properties" -ForegroundColor White

Write-Host "`n=== Test Complete ===" -ForegroundColor Green
Write-Host "Check the JWT_CENTRALIZED_MIGRATION_COMPLETE.md file for detailed documentation." -ForegroundColor Yellow
